services:
  api-gateway:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ./app:/app/app
    ports:
      - "8080:8080"
    environment:
      ORDER_SERVICE_URL: http://order-service:8001
      INVENTORY_SERVICE_URL: http://inventory-service:8002
      BILLING_SERVICE_URL: http://billing-service:8003
      NOTIFICATION_SERVICE_URL: http://notification-service:8004
      LOGGER_SERVICE_URL: http://logger-service:8005
