version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
      POSTGRES_DB: order_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  order-service:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
    environment:
      DATABASE_URL: postgresql://order_user:order_pass@db:5432/order_db
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  pgdata:
