services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: billing_user
      POSTGRES_PASSWORD: billing_pass
      POSTGRES_DB: billing_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  billing-service:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./app:/app/app
    environment:
      POSTGRES_USER: billing_user
      POSTGRES_PASSWORD: billing_pass
      POSTGRES_DB: billing_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "8002:8002"
    depends_on:
      - db
volumes:
  pgdata:
