services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_pass
      POSTGRES_DB: inventory_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  inventory-service:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./app:/app/app
    environment:
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_pass
      POSTGRES_DB: inventory_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "8001:8001"
    depends_on:
      - db
volumes:
  pgdata:
